film_master/config/routes.rb
Rails.application.routes.draw do

  	devise_for :users, :controllers => { registrations: 'registrations'}
  	match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  	
  	resources :users, :only => [:show]
 	resources :searches
  	#root page
 	get "/home" => "pages#home"
	root "pages#home"

	
	# users page 
	get "/users/:user_id" => "users#show", as: :settings

	#profile page and edits to profile
	get "/profiles" => "profiles#index"
	get "/profiles/:user_id/new" => "profiles#new", as: :new_proflie
	get "/profiles/:profile_id" => "profiles#show", as: :profile
	get "/profiles/:profile_id/edit" => "profiles#edit", as: :edit
	post "/profiles" => "profiles#create"
	patch "/profiles/:profile_id" => "profiles#update"
	

	get "/genres_profiles" => "genres_profiles#index"
	get "/genres_profiles/:profile_id/edit" => "genres_profiles#edit"
	patch "/genres_profiles/:profile_id/edit" => "genres_profiles#update"
	get "/genres_profiles/:profile_id/new" => "genres_profiles#new"
	post "/genres_profiles" => "genres_profiles#create"
	get "/genres_profiles/:profile_id" => "genres_profiles#show"

	#create page to show all movies
	get "/movies" => "movies#index", as: :movies
	get "/movies/:movie_id" => "movies#show", as: :movie


	get "/genres" => "genres#index"
	get "/genres/new" => "genres#new", :as => :genre
	post "/genres" => "genres#create"

	get "/directors" => "directors#index"
	get "/directors/new" => "directors#new", :as => :director
	post "/directors" => "directors#create"

	#ratings page
	get "/movies_users/:movie_id/:user_id" => "movies_user#index"
	get "/movies_users/:movie_id/:user_id/new" => "movies_users#new", :as => :movies_users

	get"/movies_users/:movie_id/:user_id/edit" => "movies_users#edit", :as => :movies_users_edit

	get "/movies_users/:movie_id/:user_id" => "movies_users#show", as: :movies_user

	post "/movies_users/:movie_id/:user_id/new" => "movies_users#create"

	patch "/movies_users/:movie_id/:user_id/edit" => "movies_users#update"
	delete "/movies_users/:movie_id/:rating_id" => "movies_users#destroy" , as: :destroy_rating


end

film_master/app/models/actor.rb
class Actor < ActiveRecord::Base

	has_many :roles
end

film_master/app/models/director.rb
class Director < ActiveRecord::Base

has_many :directorsMovies
has_many :movies, :through  => :directorsMovies
end

film_master/app/models/directors_movie.rb
class DirectorsMovie< ActiveRecord::Base

	belongs_to :director
	belongs_to :movie
end

film_master/app/models/genre.rb
class Genre < ActiveRecord::Base

has_many :genresMovies
has_many :movies, :through => :genresMovies

has_many :genresProfiles
has_many :profiles, :through  => :genresProfiles
end

film_master/app/models/genres_movie.rb
class GenresMovie< ActiveRecord::Base

	belongs_to :genre 
	belongs_to :movie

	
end

film_master/app/models/genres_profile.rb
class GenresProfile< ActiveRecord::Base

	belongs_to :genre 
	belongs_to :profile

	def genre_name
		genre.gName 
	end

end

film_master/app/models/movie.rb
class Movie < ActiveRecord::Base

	def self.search(search)
		  where("m_name ILIKE ?", "%#{search}%") 
	#	  where("maturity_level ILIKE ?", "%#{search}%")
	#	  where("m_name ILIKE ?",  "%#{search}%").joins(:genres).where("m_name ILIKE = ?", "%#{search}%")
	
	end


has_many :genresMovies
has_many :genres, :through  => :genresMovies

has_many :moviesUsers
has_many :users, :through  => :moviesUsers

has_many :directorsMovies
has_many :directors, :through  => :directorsMovies

has_many :moviesStudios
has_many :studios, :through  => :moviesStudios

has_many :moviesRoles
has_many :roles, :through  => :moviesRoles


end

film_master/app/models/movies_role.rb
class MoviesRole < ActiveRecord::Base

	belongs_to :movie 
	belongs_to :role
end

film_master/app/models/movies_studio.rb
class MoviesStudio < ActiveRecord::Base

	belongs_to :movie 
	belongs_to :studio
end

film_master/app/models/movies_user.rb
class MoviesUser< ActiveRecord::Base
	belongs_to :user
	belongs_to :movie


	def user_fName
		user.fName 
	end
	def user_lName
		user.lName 
	end

	# def rating
	# 	return movies_user.rating_id
	# end
	# def user_id
	# 	user.user_id
	# end
	# def self.movie_id
	# 	movie.movie_id
	# end

		#  def getRating

	 # 	rating = MoviesUser.find_by_movie_id_and_user_id(params[:movie_id],params[:user_id])
		# # genre_chosen = genres.select(:genre_id).find_by_gName(gName) 
		# # movies = movies.joins(:genres).where("genres.genre_id = ?", genre_chosen)

		# return rating
	 # end

end

film_master/app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	validates_associated :user

	has_many :genresProfiles
	has_many :genres, ->{ select("genres.gName")}, :through  => :genresProfiles

end

film_master/app/models/role.rb
class Role < ActiveRecord::Base

has_many :moviesRoles
has_many :movies, :through  => :moviesRoles

belongs_to :actor
end

film_master/app/models/search.rb
class Search < ActiveRecord::Base

		def search_movies

		movies = Movie.all 
		movies = movies.where(["m_name ILIKE ?", "%#{keywords}%"]) if keywords.present?	
	
		genres = Genre.all 
		genre_chosen = genres.select(:genre_id).find_by_gName(gName) if gName.present? 
		movies = movies.joins(:genres).where("genres.genre_id = ?", genre_chosen)

		return movies
	end
end

film_master/app/models/studio.rb
class Studio < ActiveRecord::Base

has_many :moviesStudios
has_many :movies, :through  => :moviesStudios
end

film_master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  before_create :build_profile 

has_many :moviesUsers
has_many :movies, :through  => :moviesUsers




end

film_master/app/helpers/favourites_helper.rb
module FavouritesHelper
end

film_master/app/helpers/movies_helper.rb
module MoviesHelper

	def num_movies
		if @movies.size ==1
			"#{@movies.size}"+" movie"
		else
			"#{@movies.size}"+" movies"
		end
	end


end

film_master/app/helpers/profiles_helper.rb
module ProfilesHelper

	def full_name
		@users.fName+" "+@users.lName
	end

	
end

film_master/app/helpers/searches_helper.rb
module SearchesHelper
end

film_master/app/helpers/users_helper.rb
module UsersHelper

	def full_name
		@users.fName+" "+@users.lName
	end
end

film_master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Film Master</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
</head>
<body>

	<div class="header">
	
		<nav>
		<ul>
			<li class="logo"><a href="/home"><img src="/assets/filmwhite-01.png" height="40" width="145"></a></li>
			
			<% if user_signed_in? %>
			<li ><a class="center-me" href="/movies"> Browse</a></li>
			<% end %>

			<div class="right">

			<li class="search"><%= form_tag(movies_path,:method => "get", id: "search-form") do %>
			<%= text_field_tag :search, params[:search], placeholder: "Search Movies" %>
			<%= submit_tag "Search" %></li>
			<li class="advanced"><%= link_to "Advanced Search", new_search_path %>
			<% end %></li>

			<% if user_signed_in? %>
				
				<li  class="user"> Hey <%= current_user.fName  %>!
				<div class="triangle"></div>
					<div class="user-menu">
						
						<a href="/profiles/<%= current_user.user_id %>">Profile</a>
						<a href="/users/<%= current_user.user_id %>">Settings</a>
						<%= link_to 'Sign out', destroy_user_session_path, data:{method: :delete} %>

					</div>


				</li>
			<% else %>
				<li class="sign-in"><a href="/users/sign_in"> Sign In</a></li>
				
			<% end %>
			</div>
		</ul>	
	</nav>
	</div>
	<div class= "content-container">
		<div class="content">
			<%= yield %>
		</div>
	</div>

</body>
</html>

film_master/app/views/pages/home.html.erb
<%= stylesheet_link_tag "/home.css" %>

<link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>


<% if user_signed_in? %>
<a href="/movies" class="myButton">View all Movies</a>
<% else %>
<a href="/users/sign_up" class="myButton">Sign Up Now</a>
<%end%>

<body class="home">
</body>