film_master/config/routes.rb
Rails.application.routes.draw do

  	devise_for :users, :controllers => { registrations: 'registrations'}
  	match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  	
  	resources :users, :only => [:show]
 	resources :searches
  	#root page
 	get "/home" => "pages#home"
	root "pages#home"

	
	# users page 
	get "/users/:user_id" => "users#show", as: :settings

	#profile page and edits to profile
	get "/profiles" => "profiles#index"
	get "/profiles/:user_id/new" => "profiles#new", as: :new_proflie
	get "/profiles/:profile_id" => "profiles#show", as: :profile
	get "/profiles/:profile_id/edit" => "profiles#edit", as: :edit
	post "/profiles" => "profiles#create"
	patch "/profiles/:profile_id" => "profiles#update"
	

	get "/genres_profiles" => "genres_profiles#index"
	get "/genres_profiles/:profile_id/edit" => "genres_profiles#edit"
	patch "/genres_profiles/:profile_id/edit" => "genres_profiles#update"
	get "/genres_profiles/:profile_id/new" => "genres_profiles#new"
	post "/genres_profiles" => "genres_profiles#create"
	get "/genres_profiles/:profile_id" => "genres_profiles#show"

	#create page to show all movies
	get "/movies" => "movies#index", as: :movies
	get "/movies/:movie_id" => "movies#show", as: :movie


	get "/genres" => "genres#index"
	get "/genres/new" => "genres#new", :as => :genre
	post "/genres" => "genres#create"

	get "/directors" => "directors#index"
	get "/directors/new" => "directors#new", :as => :director
	post "/directors" => "directors#create"

	#ratings page
	get "/movies_users/:movie_id/:user_id" => "movies_user#index"
	get "/movies_users/:movie_id/:user_id/new" => "movies_users#new", :as => :movies_users

	get"/movies_users/:movie_id/:user_id/edit" => "movies_users#edit", :as => :movies_users_edit

	get "/movies_users/:movie_id/:user_id" => "movies_users#show", as: :movies_user

	post "/movies_users/:movie_id/:user_id/new" => "movies_users#create"

	patch "/movies_users/:movie_id/:user_id/edit" => "movies_users#update"
	delete "/movies_users/:movie_id/:rating_id" => "movies_users#destroy" , as: :destroy_rating


end

film_master/app/models/actor.rb
class Actor < ActiveRecord::Base

	has_many :roles
end

film_master/app/models/director.rb
class Director < ActiveRecord::Base

has_many :directorsMovies
has_many :movies, :through  => :directorsMovies
end

film_master/app/models/directors_movie.rb
class DirectorsMovie< ActiveRecord::Base

	belongs_to :director
	belongs_to :movie
end

film_master/app/models/genre.rb
class Genre < ActiveRecord::Base

has_many :genresMovies
has_many :movies, :through => :genresMovies

has_many :genresProfiles
has_many :profiles, :through  => :genresProfiles
end

film_master/app/models/genres_movie.rb
class GenresMovie< ActiveRecord::Base

	belongs_to :genre 
	belongs_to :movie

	
end

film_master/app/models/genres_profile.rb
class GenresProfile< ActiveRecord::Base

	belongs_to :genre 
	belongs_to :profile

	def genre_name
		genre.gName 
	end

end

film_master/app/models/movie.rb
class Movie < ActiveRecord::Base

	def self.search(search)
		  where("m_name ILIKE ?", "%#{search}%") 
	#	  where("maturity_level ILIKE ?", "%#{search}%")
	#	  where("m_name ILIKE ?",  "%#{search}%").joins(:genres).where("m_name ILIKE = ?", "%#{search}%")
	
	end


has_many :genresMovies
has_many :genres, :through  => :genresMovies

has_many :moviesUsers
has_many :users, :through  => :moviesUsers

has_many :directorsMovies
has_many :directors, :through  => :directorsMovies

has_many :moviesStudios
has_many :studios, :through  => :moviesStudios

has_many :moviesRoles
has_many :roles, :through  => :moviesRoles


end

film_master/app/models/movies_role.rb
class MoviesRole < ActiveRecord::Base

	belongs_to :movie 
	belongs_to :role
end

film_master/app/models/movies_studio.rb
class MoviesStudio < ActiveRecord::Base

	belongs_to :movie 
	belongs_to :studio
end

film_master/app/models/movies_user.rb
class MoviesUser< ActiveRecord::Base
	belongs_to :user
	belongs_to :movie


	def user_fName
		user.fName 
	end
	def user_lName
		user.lName 
	end

	# def rating
	# 	return movies_user.rating_id
	# end
	# def user_id
	# 	user.user_id
	# end
	# def self.movie_id
	# 	movie.movie_id
	# end

		#  def getRating

	 # 	rating = MoviesUser.find_by_movie_id_and_user_id(params[:movie_id],params[:user_id])
		# # genre_chosen = genres.select(:genre_id).find_by_gName(gName) 
		# # movies = movies.joins(:genres).where("genres.genre_id = ?", genre_chosen)

		# return rating
	 # end

end

film_master/app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	validates_associated :user

	has_many :genresProfiles
	has_many :genres, ->{ select("genres.gName")}, :through  => :genresProfiles

end

film_master/app/models/role.rb
class Role < ActiveRecord::Base

has_many :moviesRoles
has_many :movies, :through  => :moviesRoles

belongs_to :actor
end

film_master/app/models/search.rb
class Search < ActiveRecord::Base

		def search_movies

		movies = Movie.all 
		movies = movies.where(["m_name ILIKE ?", "%#{keywords}%"]) if keywords.present?	
	
		genres = Genre.all 
		genre_chosen = genres.select(:genre_id).find_by_gName(gName) if gName.present? 
		movies = movies.joins(:genres).where("genres.genre_id = ?", genre_chosen)

		return movies
	end
end

film_master/app/models/studio.rb
class Studio < ActiveRecord::Base

has_many :moviesStudios
has_many :movies, :through  => :moviesStudios
end

film_master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  before_create :build_profile 

has_many :moviesUsers
has_many :movies, :through  => :moviesUsers




end

film_master/app/controllers/movies_controller.rb
class MoviesController < ApplicationController


	def index
		@movies = Movie.all

		if params[:search] 
   			 @movies = Movie.search(params[:search])
		  else 
    			@movies = Movie.all
		  end

	end

	def show
		@movies = Movie.find(params[:movie_id])

		@notReviewed = MoviesUser.where(movie_id: params[:movie_id], :user_id => current_user.user_id).empty?

		@rID = MoviesUser.select(:rating_id).where(movie_id: params[:movie_id], :user_id => current_user.user_id).to_a

		if MoviesUser.where(movie_id: params[:movie_id]).count != 0
			@overall = MoviesUser.where(movie_id: params[:movie_id]).sum(:rating) / MoviesUser.where(movie_id: params[:movie_id]).count 
		else
			@overall = 0
		end

		@movies.update(overall_rating: @overall)
		render("show")
	end

end

film_master/app/helpers/application_helper.rb
module ApplicationHelper


end

film_master/app/helpers/favourites_helper.rb
module FavouritesHelper
end

film_master/app/helpers/movies_helper.rb
module MoviesHelper

	def num_movies
		if @movies.size ==1
			"#{@movies.size}"+" movie"
		else
			"#{@movies.size}"+" movies"
		end
	end


end

film_master/app/helpers/profiles_helper.rb
module ProfilesHelper

	def full_name
		@users.fName+" "+@users.lName
	end

	
end

film_master/app/helpers/searches_helper.rb
module SearchesHelper
end

film_master/app/helpers/users_helper.rb
module UsersHelper

	def full_name
		@users.fName+" "+@users.lName
	end
end

film_master/app/views/movies/index.html.erb
  <%= stylesheet_link_tag    'movie', media: 'all', 'data-turbolinks-track' => true %>
<link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
<div class="display">
<h4> Displaying <%= num_movies %>   </h4>



			<% if @movies.present? %>
			  <%= render @movies %>
			<% else %>
			  <p>There are no movies containing the term(s) <%= params[:search] %>.</p>
			<% end %>
<div class="movielist">
	<ul>
		<% @movies.each do |movie| %>
		
	<div>
	<li>	<a href = "/movies/<%= movie.movie_id %>"> <%= image_tag "movieImages/#{movie.movie_id}.jpg", :class=>"movieImg"%> </a>
	
		<h2> <%= movie.m_name %> </h2></li>
	</div>

		<% end %>

	</ul>
</div>

film_master/app/views/movies/show.html.erb
  <%= stylesheet_link_tag    'movie', media: 'all', 'data-turbolinks-track' => true %>
<link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

<div class="title">
<h1> <%= @movies.m_name %> <span class="date">( <%= @movies.date_released %> )</span></h1>
</div>
<div class="movie-left">
	 <%= image_tag "movieImages/#{@movies.movie_id}.jpg", :class=>"movieImg"%> 
	<h3>Overall movie rating:   <%= @overall %></h3>

</div>
<div id="contentContainer">
<div id= "wrapper">

<div id="itemOne" class="movieContent">
	
	<div class="movie-right">
	<a href="/movies", data-ftrans="slide"> Back to all movies </a>
	</br>
	 <p><%= @movies.summary %></p>
	</div>
</div>
<div id="itemTwo" class="movieContent">

	 <div class="inner-left">
	 <ul>
		<h3>Genres: </h3>
		<!-- Get genres related to the movie-->
		<% @movies.genres.each do |genre| %>
		 <li> <%= genre.gName %></li>
		<% end %>
	</ul>
	<ul>	
		 <h3>  Movie Actors: </h3>
		<!-- Get actors in movie-->
		<% @movies.roles.each do |role| %>
		 <li> <%= role.actor.fName %> <%= role.actor.lName %> who plays <%= role.rName %></li>
		<% end %>
	</ul>
	<ul>
		<h3> Movie Language:</h3><span> <%= @movies.language %> </span>
	</ul>
	</div>
 	<div class="inner-right">
		 <h3>  Movie duration: </h3><span><%= @movies.duration %> minutes</span> 
		<h3>  Maturity Level:</h3> <span> <%= @movies.maturity_level %></span>


		</br>

		<h3>  Studio(s): </h3>
		<!-- Get studio that made movie-->
		<% @movies.studios.each do |studio| %>
		 <li> <%= studio.studio_name %></li>
		<% end %>

		</br>

		<h3>  Director(s): </h3>
		<!-- Get directors of the movie-->
		<% @movies.directors.each do |director| %>
		 <li> <%= director.fName %> <%= director.lName %></li>
		<% end %>
	</div>
	


<!-- List all users and  their rating of the movie IF THEY EXIST-->



	</div>
</div>
</div>
<div id="navLinks">
    <ul>
    <li class="itemLinks" data-pos="0px"></li>
        <li class="itemLinks" data-pos="-1000px"></li>
    </ul>
</div>

<div class="movie-clear">

<!-- this code allows a user to write/edit/destroy their review' -->
	<% if @notReviewed %>
		<%= link_to 'Write a review', movies_users_path(:movie_id=>@movies.movie_id, :user_id => current_user.user_id) %>
			
	<% else %>
		<%= link_to 'Edit review', movies_users_edit_path(:movie_id=>@movies.movie_id, :user_id => current_user.user_id ) %>
			<%= link_to "Delete Review", destroy_rating_path(:rating_id => @rID), data: { confirm: "Are you sure?" }, method: :delete %>
	<% end %>


<% if @movies.users.size > 0 %>
	<h2>Movie reviews</h2>
	<% @movies.moviesUsers.each do |user| %>
	 	<h4><%= user.user_fName %>  <%= user.user_lName %> -- Rated : <%= user.rating %> / 10</h4>
	 	<div class="review-body">
		 <p><%= user.body %></p>
		 </div>
	<% end %>
<% else %>
	  <p>No users have reviewed this movie.</p>
<% end %>



	<p> rate movie</p>
	<p> this requies update restfulres to update movies overallR, userMoviesRated, users_movie</p>
	</div>

<script>
 // just querying the DOM...like a boss!
var links = document.querySelectorAll(".itemLinks");
var wrapper = document.querySelector("#wrapper");
 
// the activeLink provides a pointer to the currently displayed item
var activeLink = 0;
 
// setup the event listeners
for (var i = 0; i < links.length; i++) {
    var link = links[i];
    link.addEventListener('click', setClickedItem, false);
 
    // identify the item for the activeLink
    link.itemID = i;
}
 
// set first item as active
links[activeLink].classList.add("active");
 
function setClickedItem(e) {
    removeActiveLinks();
 
    var clickedLink = e.target;
    activeLink = clickedLink.itemID;
 
    changePosition(clickedLink);
}
 
function removeActiveLinks() {
    for (var i = 0; i < links.length; i++) {
        links[i].classList.remove("active");
    }
}
 
// Handle changing the slider position as well as ensure
// the correct link is highlighted as being active
function changePosition(link) {
    var position = link.getAttribute("data-pos");
 
    var translateValue = "translate3d(" + position + ", 0px, 0)";
    wrapper.style[transformProperty] = translateValue;
 
    link.classList.add("active");
}
 
//
// Dealing with Transforms
//
var transforms = ["transform",
            "msTransform",
            "webkitTransform",
            "mozTransform",
            "oTransform"];
 
var transformProperty = getSupportedPropertyName(transforms);
 
// vendor prefix management
function getSupportedPropertyName(properties) {
    for (var i = 0; i < properties.length; i++) {
        if (typeof document.body.style[properties[i]] != "undefined") {
            return properties[i];
        }
    }
    return null;
}
</script>